# Enable OLED Display
CONFIG_ZMK_DISPLAY=y

# If you are using a wired connection, you may want to keep the OLEDs on 
# or use a longer timeout than the default
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n

# Use the dedicated status screen widgets
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_WPM_STATUS=y

# Required for some split OLED setups to initialize the peripheral side
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y